version: '3.8'

services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15
    container_name: voluntariamente_postgres
    environment:
      POSTGRES_DB: voluntariamente
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./02-populate.sql:/docker-entrypoint-initdb.d/02-populate.sql
    networks:
      - voluntariamente_network

  # Backend FastAPI
  backend:
    build: ./backend
    container_name: voluntariamente_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/voluntariamente
      - SECRET_KEY=dev-secret-key-change-in-production
      - DEBUG=true
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    networks:
      - voluntariamente_network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend Next.js
  frontend:
    build: ./CInvolunt-rio-front
    container_name: voluntariamente_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./CInvolunt-rio-front:/app
      - /app/node_modules
      - /app/.next
    networks:
      - voluntariamente_network
    command: npm run dev -- --port 3000

volumes:
  postgres_data:

networks:
  voluntariamente_network:
    driver: bridge
